import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./Providers";
import Threebg from "@/components/Threebg";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio GK",
  description: "Generated by create next app",
  favicon: "favicon.ico",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Threebg />
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
